### Create a new user
POST http://localhost:80/user
Content-Type: application/json

{
    "username": "rene"
}

### Create a new tweet
POST http://localhost:80/post
Content-Type: application/json

{
    "user_id": 16,
    "content": "ojos color sol"
}

### Follow an account
POST http://localhost:80/follow
Content-Type: application/json

{
    "follower_id": 1,
    "followed_id": 16
}

### Get timeline for a specific user
GET http://localhost:80/timeline/1
Accept: application/json

### Compliment for posts update
GET http://localhost:80/timeline/16
Accept: application/json

### cache stats
GET http://localhost:80/cache_stats